# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/langstonkosoff/Desktop/Cipher-App/ui_files/keyDisplayer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(810, 198)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_40.sizePolicy().hasHeightForWidth())
        self.lineEdit_40.setSizePolicy(sizePolicy)
        self.lineEdit_40.setFrame(True)
        self.lineEdit_40.setReadOnly(True)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.horizontalLayout_16.addWidget(self.lineEdit_40)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_42.sizePolicy().hasHeightForWidth())
        self.lineEdit_42.setSizePolicy(sizePolicy)
        self.lineEdit_42.setFrame(True)
        self.lineEdit_42.setReadOnly(True)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.horizontalLayout_16.addWidget(self.lineEdit_42)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_35.sizePolicy().hasHeightForWidth())
        self.lineEdit_35.setSizePolicy(sizePolicy)
        self.lineEdit_35.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_35.setMaxLength(1)
        self.lineEdit_35.setFrame(True)
        self.lineEdit_35.setReadOnly(True)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.horizontalLayout_16.addWidget(self.lineEdit_35)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_50.sizePolicy().hasHeightForWidth())
        self.lineEdit_50.setSizePolicy(sizePolicy)
        self.lineEdit_50.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_50.setMaxLength(1)
        self.lineEdit_50.setFrame(True)
        self.lineEdit_50.setReadOnly(True)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.horizontalLayout_16.addWidget(self.lineEdit_50)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_37.sizePolicy().hasHeightForWidth())
        self.lineEdit_37.setSizePolicy(sizePolicy)
        self.lineEdit_37.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_37.setMaxLength(1)
        self.lineEdit_37.setFrame(True)
        self.lineEdit_37.setReadOnly(True)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.horizontalLayout_16.addWidget(self.lineEdit_37)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_31.sizePolicy().hasHeightForWidth())
        self.lineEdit_31.setSizePolicy(sizePolicy)
        self.lineEdit_31.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_31.setMaxLength(1)
        self.lineEdit_31.setFrame(True)
        self.lineEdit_31.setReadOnly(True)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.horizontalLayout_16.addWidget(self.lineEdit_31)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_41.sizePolicy().hasHeightForWidth())
        self.lineEdit_41.setSizePolicy(sizePolicy)
        self.lineEdit_41.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_41.setMaxLength(1)
        self.lineEdit_41.setFrame(True)
        self.lineEdit_41.setReadOnly(True)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.horizontalLayout_16.addWidget(self.lineEdit_41)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_10.sizePolicy().hasHeightForWidth())
        self.lineEdit_10.setSizePolicy(sizePolicy)
        self.lineEdit_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_10.setMaxLength(1)
        self.lineEdit_10.setFrame(True)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_16.addWidget(self.lineEdit_10)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_38.sizePolicy().hasHeightForWidth())
        self.lineEdit_38.setSizePolicy(sizePolicy)
        self.lineEdit_38.setFrame(True)
        self.lineEdit_38.setReadOnly(True)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.horizontalLayout_16.addWidget(self.lineEdit_38)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_45.sizePolicy().hasHeightForWidth())
        self.lineEdit_45.setSizePolicy(sizePolicy)
        self.lineEdit_45.setFrame(True)
        self.lineEdit_45.setReadOnly(True)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.horizontalLayout_16.addWidget(self.lineEdit_45)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_29.sizePolicy().hasHeightForWidth())
        self.lineEdit_29.setSizePolicy(sizePolicy)
        self.lineEdit_29.setFrame(True)
        self.lineEdit_29.setReadOnly(True)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.horizontalLayout_16.addWidget(self.lineEdit_29)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_32.sizePolicy().hasHeightForWidth())
        self.lineEdit_32.setSizePolicy(sizePolicy)
        self.lineEdit_32.setFrame(True)
        self.lineEdit_32.setReadOnly(True)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.horizontalLayout_16.addWidget(self.lineEdit_32)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_44.sizePolicy().hasHeightForWidth())
        self.lineEdit_44.setSizePolicy(sizePolicy)
        self.lineEdit_44.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_44.setMaxLength(1)
        self.lineEdit_44.setFrame(True)
        self.lineEdit_44.setReadOnly(True)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.horizontalLayout_16.addWidget(self.lineEdit_44)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_16.addWidget(self.lineEdit_2)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_18.sizePolicy().hasHeightForWidth())
        self.lineEdit_18.setSizePolicy(sizePolicy)
        self.lineEdit_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_18.setMaxLength(1)
        self.lineEdit_18.setFrame(True)
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_16.addWidget(self.lineEdit_18)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_39.sizePolicy().hasHeightForWidth())
        self.lineEdit_39.setSizePolicy(sizePolicy)
        self.lineEdit_39.setFrame(True)
        self.lineEdit_39.setReadOnly(True)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.horizontalLayout_16.addWidget(self.lineEdit_39)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_49.sizePolicy().hasHeightForWidth())
        self.lineEdit_49.setSizePolicy(sizePolicy)
        self.lineEdit_49.setFrame(True)
        self.lineEdit_49.setReadOnly(True)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.horizontalLayout_16.addWidget(self.lineEdit_49)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_33.sizePolicy().hasHeightForWidth())
        self.lineEdit_33.setSizePolicy(sizePolicy)
        self.lineEdit_33.setFrame(True)
        self.lineEdit_33.setReadOnly(True)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.horizontalLayout_16.addWidget(self.lineEdit_33)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_34.sizePolicy().hasHeightForWidth())
        self.lineEdit_34.setSizePolicy(sizePolicy)
        self.lineEdit_34.setFrame(True)
        self.lineEdit_34.setReadOnly(True)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.horizontalLayout_16.addWidget(self.lineEdit_34)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_47.sizePolicy().hasHeightForWidth())
        self.lineEdit_47.setSizePolicy(sizePolicy)
        self.lineEdit_47.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_47.setMaxLength(1)
        self.lineEdit_47.setFrame(True)
        self.lineEdit_47.setReadOnly(True)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.horizontalLayout_16.addWidget(self.lineEdit_47)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_11.sizePolicy().hasHeightForWidth())
        self.lineEdit_11.setSizePolicy(sizePolicy)
        self.lineEdit_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_11.setMaxLength(1)
        self.lineEdit_11.setFrame(True)
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_16.addWidget(self.lineEdit_11)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_43.sizePolicy().hasHeightForWidth())
        self.lineEdit_43.setSizePolicy(sizePolicy)
        self.lineEdit_43.setFrame(True)
        self.lineEdit_43.setReadOnly(True)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.horizontalLayout_16.addWidget(self.lineEdit_43)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_48.sizePolicy().hasHeightForWidth())
        self.lineEdit_48.setSizePolicy(sizePolicy)
        self.lineEdit_48.setFrame(True)
        self.lineEdit_48.setReadOnly(True)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.horizontalLayout_16.addWidget(self.lineEdit_48)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_30.sizePolicy().hasHeightForWidth())
        self.lineEdit_30.setSizePolicy(sizePolicy)
        self.lineEdit_30.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_30.setMaxLength(1)
        self.lineEdit_30.setFrame(True)
        self.lineEdit_30.setReadOnly(True)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.horizontalLayout_16.addWidget(self.lineEdit_30)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_46.sizePolicy().hasHeightForWidth())
        self.lineEdit_46.setSizePolicy(sizePolicy)
        self.lineEdit_46.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_46.setMaxLength(1)
        self.lineEdit_46.setFrame(True)
        self.lineEdit_46.setReadOnly(True)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.horizontalLayout_16.addWidget(self.lineEdit_46)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_36.sizePolicy().hasHeightForWidth())
        self.lineEdit_36.setSizePolicy(sizePolicy)
        self.lineEdit_36.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_36.setMaxLength(1)
        self.lineEdit_36.setFrame(True)
        self.lineEdit_36.setReadOnly(True)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.horizontalLayout_16.addWidget(self.lineEdit_36)
        self.gridLayout.addLayout(self.horizontalLayout_16, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.a_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a_key.sizePolicy().hasHeightForWidth())
        self.a_key.setSizePolicy(sizePolicy)
        self.a_key.setDragEnabled(True)
        self.a_key.setObjectName("a_key")
        self.horizontalLayout_17.addWidget(self.a_key)
        self.b_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_key.sizePolicy().hasHeightForWidth())
        self.b_key.setSizePolicy(sizePolicy)
        self.b_key.setObjectName("b_key")
        self.horizontalLayout_17.addWidget(self.b_key)
        self.c_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c_key.sizePolicy().hasHeightForWidth())
        self.c_key.setSizePolicy(sizePolicy)
        self.c_key.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.c_key.setMaxLength(1)
        self.c_key.setObjectName("c_key")
        self.horizontalLayout_17.addWidget(self.c_key)
        self.d_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.d_key.sizePolicy().hasHeightForWidth())
        self.d_key.setSizePolicy(sizePolicy)
        self.d_key.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.d_key.setMaxLength(1)
        self.d_key.setObjectName("d_key")
        self.horizontalLayout_17.addWidget(self.d_key)
        self.e_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_key.sizePolicy().hasHeightForWidth())
        self.e_key.setSizePolicy(sizePolicy)
        self.e_key.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.e_key.setMaxLength(1)
        self.e_key.setObjectName("e_key")
        self.horizontalLayout_17.addWidget(self.e_key)
        self.f_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_key.sizePolicy().hasHeightForWidth())
        self.f_key.setSizePolicy(sizePolicy)
        self.f_key.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.f_key.setMaxLength(1)
        self.f_key.setObjectName("f_key")
        self.horizontalLayout_17.addWidget(self.f_key)
        self.g_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g_key.sizePolicy().hasHeightForWidth())
        self.g_key.setSizePolicy(sizePolicy)
        self.g_key.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.g_key.setMaxLength(1)
        self.g_key.setObjectName("g_key")
        self.horizontalLayout_17.addWidget(self.g_key)
        self.h_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.h_key.sizePolicy().hasHeightForWidth())
        self.h_key.setSizePolicy(sizePolicy)
        self.h_key.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.h_key.setMaxLength(1)
        self.h_key.setObjectName("h_key")
        self.horizontalLayout_17.addWidget(self.h_key)
        self.i_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_key.sizePolicy().hasHeightForWidth())
        self.i_key.setSizePolicy(sizePolicy)
        self.i_key.setObjectName("i_key")
        self.horizontalLayout_17.addWidget(self.i_key)
        self.j_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.j_key.sizePolicy().hasHeightForWidth())
        self.j_key.setSizePolicy(sizePolicy)
        self.j_key.setObjectName("j_key")
        self.horizontalLayout_17.addWidget(self.j_key)
        self.k_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.k_key.sizePolicy().hasHeightForWidth())
        self.k_key.setSizePolicy(sizePolicy)
        self.k_key.setObjectName("k_key")
        self.horizontalLayout_17.addWidget(self.k_key)
        self.l_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_key.sizePolicy().hasHeightForWidth())
        self.l_key.setSizePolicy(sizePolicy)
        self.l_key.setObjectName("l_key")
        self.horizontalLayout_17.addWidget(self.l_key)
        self.m_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_key.sizePolicy().hasHeightForWidth())
        self.m_key.setSizePolicy(sizePolicy)
        self.m_key.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.m_key.setMaxLength(1)
        self.m_key.setObjectName("m_key")
        self.horizontalLayout_17.addWidget(self.m_key)
        self.n_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_key.sizePolicy().hasHeightForWidth())
        self.n_key.setSizePolicy(sizePolicy)
        self.n_key.setObjectName("n_key")
        self.horizontalLayout_17.addWidget(self.n_key)
        self.o_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.o_key.sizePolicy().hasHeightForWidth())
        self.o_key.setSizePolicy(sizePolicy)
        self.o_key.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.o_key.setMaxLength(1)
        self.o_key.setObjectName("o_key")
        self.horizontalLayout_17.addWidget(self.o_key)
        self.p_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_key.sizePolicy().hasHeightForWidth())
        self.p_key.setSizePolicy(sizePolicy)
        self.p_key.setObjectName("p_key")
        self.horizontalLayout_17.addWidget(self.p_key)
        self.q_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.q_key.sizePolicy().hasHeightForWidth())
        self.q_key.setSizePolicy(sizePolicy)
        self.q_key.setObjectName("q_key")
        self.horizontalLayout_17.addWidget(self.q_key)
        self.r_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r_key.sizePolicy().hasHeightForWidth())
        self.r_key.setSizePolicy(sizePolicy)
        self.r_key.setObjectName("r_key")
        self.horizontalLayout_17.addWidget(self.r_key)
        self.s_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s_key.sizePolicy().hasHeightForWidth())
        self.s_key.setSizePolicy(sizePolicy)
        self.s_key.setObjectName("s_key")
        self.horizontalLayout_17.addWidget(self.s_key)
        self.t_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_key.sizePolicy().hasHeightForWidth())
        self.t_key.setSizePolicy(sizePolicy)
        self.t_key.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.t_key.setMaxLength(1)
        self.t_key.setObjectName("t_key")
        self.horizontalLayout_17.addWidget(self.t_key)
        self.u_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.u_key.sizePolicy().hasHeightForWidth())
        self.u_key.setSizePolicy(sizePolicy)
        self.u_key.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.u_key.setMaxLength(1)
        self.u_key.setObjectName("u_key")
        self.horizontalLayout_17.addWidget(self.u_key)
        self.v_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v_key.sizePolicy().hasHeightForWidth())
        self.v_key.setSizePolicy(sizePolicy)
        self.v_key.setObjectName("v_key")
        self.horizontalLayout_17.addWidget(self.v_key)
        self.w_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_key.sizePolicy().hasHeightForWidth())
        self.w_key.setSizePolicy(sizePolicy)
        self.w_key.setObjectName("w_key")
        self.horizontalLayout_17.addWidget(self.w_key)
        self.x_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_key.sizePolicy().hasHeightForWidth())
        self.x_key.setSizePolicy(sizePolicy)
        self.x_key.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.x_key.setMaxLength(1)
        self.x_key.setObjectName("x_key")
        self.horizontalLayout_17.addWidget(self.x_key)
        self.y_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_key.sizePolicy().hasHeightForWidth())
        self.y_key.setSizePolicy(sizePolicy)
        self.y_key.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.y_key.setMaxLength(1)
        self.y_key.setObjectName("y_key")
        self.horizontalLayout_17.addWidget(self.y_key)
        self.z_key = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_key.sizePolicy().hasHeightForWidth())
        self.z_key.setSizePolicy(sizePolicy)
        self.z_key.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.z_key.setMaxLength(1)
        self.z_key.setObjectName("z_key")
        self.horizontalLayout_17.addWidget(self.z_key)
        self.gridLayout.addLayout(self.horizontalLayout_17, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_11.setText(_translate("Form", "Cipher Text"))
        self.lineEdit_40.setText(_translate("Form", "A"))
        self.lineEdit_42.setText(_translate("Form", "B"))
        self.lineEdit_35.setText(_translate("Form", "C"))
        self.lineEdit_50.setText(_translate("Form", "D"))
        self.lineEdit_37.setText(_translate("Form", "E"))
        self.lineEdit_31.setText(_translate("Form", "F"))
        self.lineEdit_41.setText(_translate("Form", "G"))
        self.lineEdit_10.setText(_translate("Form", "H"))
        self.lineEdit_38.setText(_translate("Form", "I"))
        self.lineEdit_45.setText(_translate("Form", "J"))
        self.lineEdit_29.setText(_translate("Form", "K"))
        self.lineEdit_32.setText(_translate("Form", "L"))
        self.lineEdit_44.setText(_translate("Form", "M"))
        self.lineEdit_2.setText(_translate("Form", "N"))
        self.lineEdit_18.setText(_translate("Form", "O"))
        self.lineEdit_39.setText(_translate("Form", "P"))
        self.lineEdit_49.setText(_translate("Form", "Q"))
        self.lineEdit_33.setText(_translate("Form", "R"))
        self.lineEdit_34.setText(_translate("Form", "S"))
        self.lineEdit_47.setText(_translate("Form", "T"))
        self.lineEdit_11.setText(_translate("Form", "U"))
        self.lineEdit_43.setText(_translate("Form", "V"))
        self.lineEdit_48.setText(_translate("Form", "W"))
        self.lineEdit_30.setText(_translate("Form", "X"))
        self.lineEdit_46.setText(_translate("Form", "Y"))
        self.lineEdit_36.setText(_translate("Form", "Z"))
        self.label_12.setText(_translate("Form", "Plain Text:"))
        self.a_key.setText(_translate("Form", "A"))
        self.b_key.setText(_translate("Form", "B"))
        self.c_key.setText(_translate("Form", "C"))
        self.d_key.setText(_translate("Form", "D"))
        self.e_key.setText(_translate("Form", "E"))
        self.f_key.setText(_translate("Form", "F"))
        self.g_key.setText(_translate("Form", "G"))
        self.h_key.setText(_translate("Form", "H"))
        self.i_key.setText(_translate("Form", "I"))
        self.j_key.setText(_translate("Form", "J"))
        self.k_key.setText(_translate("Form", "K"))
        self.l_key.setText(_translate("Form", "L"))
        self.m_key.setText(_translate("Form", "M"))
        self.n_key.setText(_translate("Form", "N"))
        self.o_key.setText(_translate("Form", "s"))
        self.p_key.setText(_translate("Form", "P"))
        self.q_key.setText(_translate("Form", "Q"))
        self.r_key.setText(_translate("Form", "R"))
        self.s_key.setText(_translate("Form", "S"))
        self.t_key.setText(_translate("Form", "T"))
        self.u_key.setText(_translate("Form", "U"))
        self.v_key.setText(_translate("Form", "V"))
        self.w_key.setText(_translate("Form", "W"))
        self.x_key.setText(_translate("Form", "X"))
        self.y_key.setText(_translate("Form", "Y"))
        self.z_key.setText(_translate("Form", "Z"))

